// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.ReadFlexVolumeController.Get~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{PostgreKeyRotation.Models.FlexVolumeResult}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.ReadFlexVolumeController.Get~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{PostgreKeyRotation.Models.FlexVolumeResult}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.ReadFlexVolumeController.#ctor(Microsoft.Extensions.Logging.ILogger{PostgreKeyRotation.Controllers.ReadFlexVolumeController},Microsoft.Extensions.Options.IOptions{PostgreKeyRotation.Models.ReadFlexVolumeControllerConfig})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.ReadFlexVolumeController.Get~System.Threading.Tasks.Task{PostgreKeyRotation.Models.FlexVolumeResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.ReadFlexVolumeController.Get~System.Threading.Tasks.Task{PostgreKeyRotation.Models.FlexVolumeResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.PostgreSQLController.GetConnectionStringAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.PostgreSQLController.GetConnectionStringAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.PostgreSQLController.Get~System.Threading.Tasks.Task{PostgreKeyRotation.Models.PostgresSQLConnectResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:PostgreKeyRotation.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PostgreKeyRotation.Controllers.PostgreSQLController.GetConnectionStringAsync~System.Threading.Tasks.Task{System.String}")]
